function [X1,Y1,O,F] = poly(Omega_0,Omega_T,T,fi_0,fi_T,t,x_0,x_T,y_0,y_T)
%POLY
%    [X1,Y1,O,F] = POLY(OMEGA_0,OMEGA_T,T,FI_0,FI_T,T,X_0,X_T,Y_0,Y_T)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    09-Jun-2021 22:57:19

t2 = t.^2;
t3 = t.^3;
t5 = -Omega_0;
t6 = 1.0./T;
t9 = -fi_T;
t10 = -x_T;
t11 = -y_T;
t4 = t2.^2;
t7 = t6.^2;
t8 = t6.^3;
t12 = fi_0+t9;
t13 = t10+x_0;
X1 = x_0-t.*t6.*t13;
if nargout > 1
    t14 = t13.^2;
    t15 = Omega_0.*t13;
    t16 = fi_0.*t13;
    t17 = 1.0./t13;
    t19 = t5.*t13;
    t20 = t6.*t12.*3.0;
    t21 = t7.*t12.*2.4e+1;
    t22 = t8.*t12.*3.0e+1;
    t18 = 1.0./t14;
    t23 = (fi_0.*t14)./2.0;
    t24 = Omega_T+t5+t16;
    t25 = t11+t19+t23+y_0;
    t26 = t6.*t17.*t24.*2.4e+1;
    t28 = t7.*t17.*t24.*1.68e+2;
    t29 = t8.*t17.*t24.*1.8e+2;
    t27 = -t26;
    t30 = -t28;
    t31 = -t29;
    t32 = t6.*t18.*t25.*6.0e+1;
    t33 = t7.*t18.*t25.*3.6e+2;
    t34 = t8.*t18.*t25.*3.6e+2;
    t35 = t20+t27+t32;
    t36 = t21+t30+t33;
    t37 = t22+t31+t34;
    Y1 = y_0+t.*t6.*t19+t2.*t7.*t23-(t3.*t7.*t14.*t35)./6.0+(t4.*t7.*t14.*t36)./2.4e+1-(t.^5.*t7.*t14.*t37)./6.0e+1;
end
if nargout > 2
    O = Omega_0-t.*t6.*t16+(t2.*t6.*t13.*t35)./2.0-(t3.*t6.*t13.*t36)./6.0+(t4.*t6.*t13.*t37)./1.2e+1;
end
if nargout > 3
    F = fi_0-t.*t35-t3.*(t8.*t12.*1.0e+1-t8.*t17.*t24.*6.0e+1+t8.*t18.*t25.*1.2e+2)+t2.*(t7.*t12.*1.2e+1-t7.*t17.*t24.*8.4e+1+t7.*t18.*t25.*1.8e+2);
end
